package gov.nist.hit.hl7.igamt.common.base.domain;

public enum Type {

  IGDOCUMENT("IGDOCUMENT"),
  DATATYPEREGISTRY("DATATYPEREGISTRY"),
  DERIVEDDATATYPEREGISTRY("DERIVEDDATATYPEREGISTRY"),
  CONFORMANCESTATEMENTREGISTRY("CONFORMANCESTATEMENTREGISTRY"),
  CONFORMANCESTATEMENTSUMMARY("CONFORMANCESTATEMENTSUMMARY"),
  SEGMENTREGISTRY("SEGMENTREGISTRY"),
  VALUESETREGISTRY("VALUESETREGISTRY"),
  PROFILECOMPONENTREGISTRY("PROFILECOMPONENTREGISTRY"),
  COMPOSITEPROFILEREGISTRY("COMPOSITEPROFILEREGISTRY"),
  COCONSTRAINTGROUPREGISTRY("COCONSTRAINTGROUPREGISTRY"),
  COCONSTRAINTGROUP("COCONSTRAINTGROUP"),
  COCONSTRAINTBINDINGS("COCONSTRAINTBINDINGS"),
  DATATYPE("DATATYPE"),
  VALUESET("VALUESET"),
  CODE("CODE"),
  CONFORMANCEPROFILE("CONFORMANCEPROFILE"),
  SEGMENT("SEGMENT"),
  PROFILECOMPONENT("PROFILECOMPONENT"),
  COMPOSITEPROFILE("COMPOSITEPROFILE"),
  SEGMENTREF("SEGMENTREF"),
  GROUP("GROUP"),
  FIELD("FIELD"),
  COMPONENT("COMPONENT"),
  SUBCOMPONENT("SUBCOMPONENT"),
  TEXT("TEXT"),
  PROFILE("PROFILE"),
  CONFORMANCEPROFILEREGISTRY("CONFORMANCEPROFILEREGISTRY"),
  DISPLAY("DISPLAY"),
  EVENT("EVENT"),
  EVENTS("EVENTS"),
  BINDING("BINDING"),
  SECTION("SECTION"),
  DYNAMICMAPPING("DYNAMICMAPPING"),
  CONFORMANCESTATEMENT("CONFORMANCESTATEMENT"),
  PREDICATE("PREDICATE"),
  DATATYPELIBRARY("DATATYPELIBRARY"),
  MESSAGESTRUCTUREREGISTRY("MESSAGESTRUCTUREREGISTRY"),
  SEGMENTCONTEXT("SEGMENTCONTEXT"),
  PROFILECOMPONENTITEM("PROFILECOMPONENTITEM"),
  MESSAGESTRUCTURE("MESSAGESTRUCTURE"),
  MESSAGECONTEXT("MESSAGECONTEXT"),
  WORKSPACE("WORSPACE"),
  FOLDER("FOLDER"),
  CODESET("CODESET"),
  CODESETVERSION("CODESETVERSION");

  Type(String value) {
    this.value = value;
  }
  private final String value;

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    // TODO Auto-generated method stub
    return this.value;
  }

  public static Type fromString(String text) {
    for (Type t : Type.values()) {
      if (t.value.equalsIgnoreCase(text)) {
        return t;
      }
    }
    return null;
  }

}
