package gov.nist.hit.hl7.igamt.shared.domain;

public enum Type {
IGDOCUMENT,
DATATYPEREGISTRY,
SEGMENTRGISTRY,
VALUESETREGISTRY,
MESSAGEREGISTRY,
PROFILECOMPONENTREGISTRY,
COMPOSITEPROFILEREGISTRY,
DATATYPE,
VALUESET,
CONFORMANCEPROFILE,
SEGMENT,
PROFILECOMPONENT,
COMPOSITEPROFILE,
SEGMENTREF,
GROUP,
FIELD,
COMPONENT,
TEXT,
PROFILE, CONFORMANCEPROFILEREGISTRY,
DISPLAY,
EVENT,EVENTS,
BINDING

}
