<project
    xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>gov.nist.hit.hl7</groupId>
    <artifactId>common</artifactId>
    <version>0.0.1-SNAPSHOT</version>
  </parent>
  <artifactId>common-minidump</artifactId>
  <name>common-minidump</name>
  <dependencies>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-mongodb</artifactId>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
    </dependency>
    <dependency>
      <groupId>gov.nist.hit.hl7</groupId>
      <artifactId>common-base</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>gov.nist.hit.hl7</groupId>
      <artifactId>ig</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>gov.nist.hit.hl7</groupId>
      <artifactId>datatype-library</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>gov.nist.hit.hl7</groupId>
      <artifactId>valueset</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>gov.nist.hit.hl7</groupId>
      <artifactId>workspace</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>gov.nist.hit.hl7</groupId>
      <artifactId>export-configuration</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>gov.nist.hit.hl7</groupId>
      <artifactId>common-config</artifactId>
      <version>${project.version}</version>
    </dependency>
  </dependencies>
</project>
