/**
 * Created by ena3 on 6/5/18.
 */
export enum Scopes{

  HL7STANDARD="HL7STANDARD",
    MASTER="MASTER", USER="USER", PRELOADED="PRELOADED", PHINVADS="PHINVADS", INTERMASTER="INTERMASTER", ARCHIVED="ARCHIVED"

}
