/**
 * Created by ena3 on 6/5/18.
 */
export enum Types{
  IGDOCUMENT="IGDOCUMENT",
  DATATYPEREGISTRY="DATATYPEREGISTRY",
  DERIVEDDATATYPEREGISTRY="DERIVEDDATATYPEREGISTRY",
  SEGMENTREGISTRY="SEGMENTREGISTRY",
  VALUESETREGISTRY="VALUESETREGISTRY",
  PROFILECOMPONENTREGISTRY="PROFILECOMPONENTREGISTRY",
  COMPOSITEPROFILEREGISTRY="COMPOSITEPROFILEREGISTRY",
  DATATYPE="DATATYPE",
  VALUESET="VALUESET",
  CONFORMANCEPROFILE="CONFORMANCEPROFILE",
  SEGMENT="SEGMENT",
  PROFILECOMPONENT="PROFILECOMPONENT",
  COMPOSITEPROFILE="COMPOSITEPROFILE",
  SEGMENTREF="SEGMENTREF",
  GROUP="GROUP",
  FIELD="FIELD",
  COMPONENT="COMPONENT",
  TEXT="TEXT",
  PROFILE="PROFILE", CONFORMANCEPROFILEREGISTRY="CONFORMANCEPROFILEREGISTRY",
  DISPLAY="DISPLAY",
  EVENT="EVENT",EVENTS="EVENTS",
  BINDING="BINDING",
  SECTION="SECTION",
  DYNAMICMAPPING="DYNAMICMAPPING"


}
