import { Type } from '../constants/type.enum';

export interface IEditorMetadata {
  id: EditorID;
  title?: string;
  resourceType?: Type;
}

export enum EditorID {
  IG_METADATA = 'IG_METADATA',
  SEGMENT_METADATA = 'SEGMENT_METADATA',
  DATATYPE_METADATA = 'DATATYPE_METADATA',
  MESSAGE_METADATA = 'MESSAGE_METADATA',
  VALUESET_METADATA = 'VALUESET_METADATA',
  SECTION_NARRATIVE = 'SECTION_NARRATIVE',
  PREDEF = 'PREDEF',
  POSTDEF = 'POSTDEF',
  CROSSREF = 'CROSSREF',
  CONFP_STRUCTURE = 'CONFP_STRUCTURE',
  SEGMENT_STRUCTURE = 'SEGMENT_STRUCTURE',
  SEGMENT_CS = 'SEGMENT_CS',
  DATATYPE_CS = 'DATATYPE_CS',
  CP_CS = 'CP_CS',
  DATATYPE_STRUCTURE = 'DATATYPE_STRUCTURE',
  VALUESET_STRUCTURE = 'VALUESET_STRUCTURE',
  DATATYPE_DELTA = 'DATATYPE_DELTA',
  SEGMENT_DELTA = 'SEGMENT_DELTA',
  CONFP_DELTA = 'CONFP_DELTA',
  DYNAMIC_MAPPING = 'DYNAMIC_MAPPING',

}
